### ISSUE TITLE
Great work, thanks for releasing this

### ISSUE THREAD

**Issue by TreyWi** [adrian-casanova/disney_park_reservation_bot#1]
A couple notes: Great work, the instructions left a bit of things unclear to me but you saved me a lot of time.
You probably want to have NPM and node installed to load all the packages you need to run this. EG sudo npm install node

the .env file is just:
email=notarealemail@gmail.com
password=notarealpassword
date=2021-06-14

The system as it exists today will log out and stop searching after about 15 minutes depending on disney's servers not your own. You just need to rekick it off. (Or program a work around to re-login). Enhancement suggestions include the option to hardcode your people/park so you don't have to select them. For those who don't know how the system works, each park reservation is a unique ID, when people change their plans at random times throughout the day this system will catch that released unique ID and associate it to your account. There is no rhythm for when people release but keep trying and you'll catch one eventually. Frequently at the day before plans change

**Comment by txcrew** [comment]
Thanks for the extra tips @TreyWi. I was able to get mostly up and running after updating NPM. 

Should `.env` be at the root? After `run.sh` I'm getting `Email or password not set in .env file`. I'm assuming it's just not finding the file because the contents is correct. Any additional tips would be much appreciated.

**Comment by cvn0va** [comment]
Hey sorry i just saw this i can implement a refresh of the token so that you dont get kicked out every 15 minutes. Disney just updated their login method which i just had to update so i can work on making the refresh work .
Thanks for the feedback

**Comment by cvn0va** [comment]
> Thanks for the extra tips @TreyWi. I was able to get mostly up and running after updating NPM.
> 
> Should `.env` be at the root? After `run.sh` I'm getting `Email or password not set in .env file`. I'm assuming it's just not finding the file because the contents is correct. Any additional tips would be much appreciated.

Yes the .env file should be at the root

**Comment by divincenzo** [comment]
Thank you for creating this! I've been working away at this tonight and I think I've almost got it up and running. After run.sh i get the following:
```
tokensCached:  false
Unable to get inputs
```

does this mean my .env file setup incorrectly?
