### ISSUE TITLE
Bots kick me out after 15 mins or so.

### ISSUE THREAD

**Issue by wonkyfist** [adrian-casanova/disney_park_reservation_bot#4]
How come the bot stop working between 15-20 mins of runtime?

whats the verdict on this issue? Making a little tough snatching a reservation on a tough day when it stops working randomly.

**Comment by cvn0va** [comment]
I'm currently working on refreshing the token it should be out today or tomorrow.

**Comment by wonkyfist** [comment]
> I'm currently working on refreshing the token it should be out today or tomorrow.

Thats good to hear , i'll wait for it then before continue trying

**Comment by cvn0va** [comment]
> > I'm currently working on refreshing the token it should be out today or tomorrow.
> 
> Thats good to hear , i'll wait for it then before continue trying
I just pushed a new commit. It refreshes the token when expired so you shouldn't get kicked out anymore.

You should see this trace in the console to let you know that its working whenever your token expires
```
Some other error:  Request failed with status code 401
REFRESHING TOKENS
TOKENS REFRESHED
```
 
and then it will continue

let me know if it works

**Comment by wonkyfist** [comment]
> > > I'm currently working on refreshing the token it should be out today or tomorrow.
> > 
> > 
> > Thats good to hear , i'll wait for it then before continue trying
> > I just pushed a new commit. It refreshes the token when expired so you shouldn't get kicked out anymore.
> 
> You should see this trace in the console to let you know that its working whenever your token expires
> 
> ```
> Some other error:  Request failed with status code 401
> REFRESHING TOKENS
> TOKENS REFRESHED
> ```
> 
> and then it will continue
> 
> let me know if it works

the bot stopped

There are no slots available
Sleeping 5 seconds before next attempt
Some other error:  Request failed with status code 500
Mac-mini ~ %

**Comment by wonkyfist** [comment]
After that status code error 500 , i restarted the bot. IT gave that error you mention and continued on.

There are no slots available
Sleeping 5 seconds before next attempt
Some other error:  Request failed with status code 401
REFRESHING TOKENS
TOKENS REFRESHED
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt


SO what is it that causes that code 500 and stops it completely?

**Comment by wonkyfist** [comment]
Also got 

Sleeping 5 seconds before next attempt
There are no slots available
Sleeping 5 seconds before next attempt
Some other error:  read ETIMEDOUT
Mac-mini ~ % 

which stops it completely

**Comment by wonkyfist** [comment]
But granted i have been running it for past hour straight with no stopping at all. So aslong as theres no error that stop it , the token refresh continues

**Comment by cvn0va** [comment]
Okay that is interesting it could be a timeout or some error with their server that can happen I will make it that it retries a couple of times before fully stopping.

**Comment by wonkyfist** [comment]
> Okay that is interesting it could be a timeout or some error with their server that can happen I will make it that it retries a couple of times before fully stopping.

Great :), soo far is an awesome bot
